### ISSUE TITLE
Wifi scanning fails seemingly due to invalid access point SSID

### ISSUE THREAD

**Issue by krigga** [esp-rs/esp-idf-svc#291]
I'm trying to run a program similar to https://github.com/esp-rs/std-training/blob/main/intro/http-client/examples/http_client.rs

After scanning, I see the following:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 11, error_len: Some(1) }', /home/krigga/.cargo/registry/src/index.crates.io-6f17d22bba15001f/esp-idf-svc-0.46.2/src/private/cstr.rs:30:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

abort() was called at PC 0x400fdac6 on core 0
0x400fdac6 - panic_abort::__rust_start_panic::abort
    at /home/krigga/.rustup/toolchains/esp/lib/rustlib/src/rust/library/panic_abort/src/lib.rs:42


Backtrace: 0x40082b12:0x3ffb9b10 0x400887e5:0x3ffb9b30 0x4008ec92:0x3ffb9b50 0x400fdac6:0x3ffb9bc0 0x400fdaba:0x3ffb9be0 0x400e1842:0x3ffb9c00 0x400e17f4:0x3ffb9c50 0x400eed97:0x3ffb9cc0 0x400eec5c:0x3ffb9cf0 0x400e1582:0x3ffb9d10 0x4010a364:0x3ffb9d40 0x4010be7b:0x3ffb9d80 0x400da09c:0x3ffb9de0 0x400da1c2:0x3ffb9e10 0x400dc452:0x3ffb9e40 0x400db965:0x3ffb9e90 0x400dbc49:0x3ffb9f40 0x400dba99:0x3ffb9ff0 0x400d816f:0x3ffba090 0x400d8098:0x3ffba0d0 0x400d8c82:0x3ffba150 0x400d60b6:0x3ffba170 0x400d5afd:0x3ffba500 0x40188bdf:0x3ffba530 0x400d7144:0x3ffba550 0x400ecd3a:0x3ffba570 0x400d7134:0x3ffba5a0 0x400d5b8b:0x3ffba5d0 0x400dee33:0x3ffba5f0 0x4018d0fb:0x3ffba610
0x40082b12 - panic_abort
    at /home/krigga/dev/tmp/esp-rs-test/test1/.embuild/espressif/esp-idf/v4.4.5/components/esp_system/panic.c:408
0x3ffb9b10 - _heap_start
    at ??:??
0x400887e5 - esp_system_abort
    at /home/krigga/dev/tmp/esp-rs-test/test1/.embuild/espressif/esp-idf/v4.4.5/components/esp_system/esp_system.c:137
0x3ffb9b30 - _heap_start
    at ??:??
0x4008ec92 - abort
    at /home/krigga/dev/tmp/esp-rs-test/test1/.embuild/espressif/esp-idf/v4.4.5/components/newlib/abort.c:46
0x3ffb9b50 - _heap_start
    at ??:??
0x400fdac6 - panic_abort::__rust_start_panic::abort
    at /home/krigga/.rustup/toolchains/esp/lib/rustlib/src/rust/library/panic_abort/src/lib.rs:42
0x3ffb9bc0 - _heap_start
    at ??:??
0x400fdaba - __rust_start_panic
    at /home/krigga/.rustup/toolchains/esp/lib/rustlib/src/rust/library/panic_abort/src/lib.rs:37
0x3ffb9be0 - _heap_start
    at ??:??
0x400e1842 - rust_panic
    at /home/krigga/.rustup/toolchains/esp/lib/rustlib/src/rust/library/std/src/panicking.rs:755
0x3ffb9c00 - _heap_start
    at ??:??
0x400e17f4 - std::panicking::rust_panic_with_hook
    at ??:??
0x3ffb9c50 - _heap_start
    at ??:??
0x400eed97 - std::panicking::begin_panic_handler::{{closure}}
    at ??:??
0x3ffb9cc0 - _heap_start
    at ??:??
0x400eec5c - std::sys_common::backtrace::__rust_end_short_backtrace
    at /home/krigga/.rustup/toolchains/esp/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:151
0x3ffb9cf0 - _heap_start
    at ??:??
0x400e1582 - rust_begin_unwind
    at /home/krigga/.rustup/toolchains/esp/lib/rustlib/src/rust/library/std/src/panicking.rs:593
0x3ffb9d10 - _heap_start
    at ??:??
0x4010a364 - core::panicking::panic_fmt
    at /home/krigga/.rustup/toolchains/esp/lib/rustlib/src/rust/library/core/src/panicking.rs:67
0x3ffb9d40 - _heap_start
    at ??:??
0x4010be7b - core::result::unwrap_failed
    at /home/krigga/.rustup/toolchains/esp/lib/rustlib/src/rust/library/core/src/result.rs:1651
0x3ffb9d80 - _heap_start
    at ??:??
0x400da09c - core::result::Result<T,E>::unwrap
    at /home/krigga/.rustup/toolchains/esp/lib/rustlib/src/rust/library/core/src/result.rs:1076
0x3ffb9de0 - _heap_start
    at ??:??
0x400da1c2 - esp_idf_svc::private::cstr::from_cstr
    at /home/krigga/.cargo/registry/src/index.crates.io-6f17d22bba15001f/esp-idf-svc-0.46.2/src/private/cstr.rs:28
0x3ffb9e10 - _heap_start
    at ??:??
0x400dc452 - esp_idf_svc::wifi::<impl core::convert::From<esp_idf_svc::private::common::Newtype<&esp_idf_sys::bindings::wifi_ap_record_t>> for embedded_svc::wifi::AccessPointInfo>::from
    at /home/krigga/.cargo/registry/src/index.crates.io-6f17d22bba15001f/esp-idf-svc-0.46.2/src/wifi.rs:263
0x3ffb9e40 - _heap_start
    at ??:??
0x400db965 - <T as core::convert::Into<U>>::into
    at /home/krigga/.rustup/toolchains/esp/lib/rustlib/src/rust/library/core/src/convert/mod.rs:717
0x3ffb9e90 - _heap_start
    at ??:??
0x400dbc49 - alloc::vec::Vec<T,A>::extend_desugared
    at /home/krigga/.rustup/toolchains/esp/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:2811
0x3ffb9f40 - _heap_start
    at ??:??
0x400dba99 - <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
    at /home/krigga/.rustup/toolchains/esp/lib/rustlib/src/rust/library/alloc/src/vec/spec_extend.rs:17
0x3ffb9ff0 - _heap_start
    at ??:??
0x400d816f - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
    at /home/krigga/.rustup/toolchains/esp/lib/rustlib/src/rust/library/alloc/src/vec/spec_from_iter.rs:33
0x3ffba090 - _heap_start
    at ??:??
0x400d8098 - esp_idf_svc::wifi::WifiDriver::scan
    at /home/krigga/.cargo/registry/src/index.crates.io-6f17d22bba15001f/esp-idf-svc-0.46.2/src/wifi.rs:751
0x3ffba0d0 - _heap_start
    at ??:??
0x400d8c82 - esp_idf_svc::wifi::EspWifi::scan
    at /home/krigga/.cargo/registry/src/index.crates.io-6f17d22bba15001f/esp-idf-svc-0.46.2/src/wifi.rs:1405
0x3ffba150 - _heap_start
    at ??:??
0x400d60b6 - <&mut W as embedded_svc::wifi::Wifi>::scan
    at /home/krigga/.cargo/registry/src/index.crates.io-6f17d22bba15001f/embedded-svc-0.25.3/src/wifi.rs:407
0x3ffba170 - _heap_start
    at ??:??
0x400d5afd - test1::main
    at /home/krigga/dev/tmp/esp-rs-test/test1/src/main.rs:90
0x3ffba500 - _heap_start
    at ??:??
0x40188bdf - core::ops::function::FnOnce::call_once
    at /home/krigga/.rustup/toolchains/esp/lib/rustlib/src/rust/library/core/src/ops/function.rs:250
0x3ffba530 - _heap_start
    at ??:??
0x400d7144 - std::rt::lang_start::{{closure}}
    at /home/krigga/.rustup/toolchains/esp/lib/rustlib/src/rust/library/std/src/rt.rs:166
0x3ffba550 - _heap_start
    at ??:??
0x400ecd3a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
    at /home/krigga/.rustup/toolchains/esp/lib/rustlib/src/rust/library/core/src/ops/function.rs:284
0x3ffba570 - _heap_start
    at ??:??
0x400d7134 - std::rt::lang_start
    at /home/krigga/.rustup/toolchains/esp/lib/rustlib/src/rust/library/std/src/rt.rs:165
0x3ffba5a0 - _heap_start
    at ??:??
0x400d5b8b - main
    at ??:??
0x3ffba5d0 - _heap_start
    at ??:??
0x400dee33 - app_main
    at /home/krigga/.cargo/registry/src/index.crates.io-6f17d22bba15001f/esp-idf-sys-0.33.2/src/start.rs:49
0x3ffba5f0 - _heap_start
    at ??:??
0x4018d0fb - main_task
    at /home/krigga/dev/tmp/esp-rs-test/test1/.embuild/espressif/esp-idf/v4.4.5/components/freertos/port/port_common.c:141
0x3ffba610 - _heap_start
    at ??:??
```

Then it reboots and it goes all over again.

**Comment by krigga** [comment]
I made a small PR with a fix but as is it probably isn't very good https://github.com/esp-rs/esp-idf-svc/pull/292
